site_name: MAL C API
pages:
- Home: index.md
- Tutorial: tutorial.md
- 'MAL APIs':
    - 'Attributes': mal_attributes.md
    - 'Encoding': mal_encoding.md
    - 'MAL': mal_api.md
    - 'Transport': mal_transport.md
    - 'Area': area.md
    - 'Actor': mal_actor.md
- Transports:
    - 'MAL/CZMQ': mal_czmq.md
- Generators:
    - 'Stubs generator': stub_generator.md
    - 'MalBinary': malbinary_generator.md
- Annexs: annexes.md
